In [1]:
import numpy as np

#Creating np.arrays

In [2]:
arr = np.array([1,2,3,4,5])
print(arr) # [1 2 3 4 5]

[1 2 3 4 5]


In [3]:
print(type(arr)) # <class 'numpy.ndarray'>

<class 'numpy.ndarray'>


In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])  # [2 3 4 5]
print(type(arr[1:5])) # <class 'numpy.ndarray'>


[2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
arr.dtype # dtype('int64')

dtype('int64')

In [6]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype) # <U6

<U6


In [7]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [8]:
arr = np.array([1,2,3,4,5])
y = arr.view()
arr[0] = 42
print(arr)
print(y)

[42  2  3  4  5]
[42  2  3  4  5]


In [9]:
y[0] = 1
print(arr)
print(y)

[1 2 3 4 5]
[1 2 3 4 5]


In [10]:
print(arr.shape) # (5,)

(5,)


In [11]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape) 

(2, 4)


In [12]:
arr = np.array([1,2,3,4], ndmin = 5)
print(arr)
print(arr.shape)
print(arr.shape[-1])

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)
4


In [13]:
arr = np.array([1,2,3,4])
print(arr.ndim)
print(arr[0])

1
1


In [14]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr[1, 1, 0])

7


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[arr%2==0])
print(arr[1::2])

[2 4 6]
[2 4 6]


In [16]:
b = arr[1:5]
print(b)
c = arr[1:5].copy()
print(c)

[2 3 4 5]
[2 3 4 5]


In [17]:
print(b.base)
print(c.base)

[1 2 3 4 5 6 7]
None


In [18]:
arr = np.arange(1,9).reshape(2,2,-1)
arr.shape

(2, 2, 2)

In [19]:
a = np.array([1, 2])
b = np.array([3, 4])
print(np.stack((a, b)))
print(np.hstack((a, b)))
print(np.vstack((a, b)))
print(np.dstack((a, b)))
print(np.concatenate((a, b)))

[[1 2]
 [3 4]]
[1 2 3 4]
[[1 2]
 [3 4]]
[[[1 3]
  [2 4]]]
[1 2 3 4]


In [20]:
A = np.array([3, 4, 5])
B = np.array([1,9,0])
print(np.dstack((A,B)))

[[[3 1]
  [4 9]
  [5 0]]]


In [21]:
A = np.array([[3, 4, 5]])
B = np.array([[1,9,0]])
print(np.dstack((A,B)))

[[[3 1]
  [4 9]
  [5 0]]]


In [23]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.dstack((arr1, arr2)))
print(np.stack((arr1, arr2)))
print(np.stack((arr1, arr2), axis = 1))

[[[1 4]
  [2 5]
  [3 6]]]


TypeError: dstack() got an unexpected keyword argument 'axis'

In [25]:
print(np.stack((arr1, arr2)))
print(np.concatenate((arr1, arr2)))
print(np.stack((arr1, arr2), axis = 1))
print(np.concatenate((arr1, arr2), axis = 1))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


AxisError: axis 1 is out of bounds for array of dimension 1

In [29]:
a = np.array([[1, 2], [3,4]])
b = np.array([[5, 6], [7,8]])
print(np.stack((a, b)))
print(np.concatenate((a, b)))
print(np.stack((a, b), axis = 1))
print(np.concatenate((a, b), axis = 1))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
[[1 2 5 6]
 [3 4 7 8]]


In [30]:
a = np.array([[1, 2], [3,4]])
b = np.array([[5, 6], [7,8]])
print(np.stack((a, b)))
print(np.stack((a, b), axis = 1))
print(np.stack((a, b), axis = 2))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [31]:
from numpy import random
x = random.rand(3, 5)
print(x)

[[0.97666297 0.06507566 0.4203196  0.74523183 0.70693026]
 [0.18943718 0.93758026 0.96324985 0.01454006 0.99587038]
 [0.10466317 0.06705424 0.62495833 0.06182475 0.99547816]]


In [32]:
print(a*b)

[[ 5 12]
 [21 32]]


In [39]:
arr = np.array(['banana', 'cherry', 'apple'])
print(arr.sort())
print(np.sort(arr).base)
print(np.sort(arr)[::-1].base)

None
None
['apple' 'banana' 'cherry']


In [40]:
arr = np.array([1, 0, 3])
print(arr.astype(bool))
print(arr.astype(bool).base)

[ True False  True]
None


In [42]:
arr = np.array([1, 2, 3, 4], dtype='S')
arr

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [43]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
e = arr1*arr2
print(e.sum())
print(np.sum(e))

32
32
